config/routes.rb
Rails.application.routes.draw do
  root "cocktails#index"

  resources :cocktails, only: [:index, :show, :new, :edit, :update, :create, :destroy] do
    resources :doses, only: [:new, :create, :destroy], shallow: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord

  validates :name, presence: true, allow_nil: false
  validates :name, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  mount_uploader :photo, PhotoUploader

end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates_uniqueness_of :ingredient, scope: :cocktail
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true, allow_nil: false
  has_many :doses, dependent: :nullify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  before_action :set_cocktail, only: [:update, :edit, :show, :destroy]

  def home

  end

  def index
    @cocktails = Cocktail.all

  end

  def show
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end


  def destroy
    @cocktail.destroy
    redirect_to root_path
  end

  def photo
    @cocktail = Cocktail.find(params[:id], [:photo])
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :photo_cache, :description)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:create, :edit, :update]

  def create
    # @dose = Dose.new(dose_params)
    # @dose.cocktail = @cocktail

    @dose = @cocktail.doses.new(dose_params)
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render "cocktails/show"
    end
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:ingredient_id, :quantitée)
  end
end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper

end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/layouts_helper.rb
module LayoutsHelper
end

app/views/cocktails/_form.html.erb
<div class="container">
  <div class="offset-top">
    <div class="row">
      <div class="col-md-4">
        <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name, placeholder: 'Enter a name for this cocktail' %>
        <%= f.input :description, as: :text, placeholder: 'Enter a description for this cocktail' %>
        <%= f.input :photo, label: 'Add a photo' %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
      </div>
    </div>
  </div>
  <br>
<p class="warning">Once your cocktail is create you can update it and change doses by accessing them from the home page !</p>
</div>

app/views/cocktails/edit.html.erb
<%= render 'cocktails/form' %>

app/views/cocktails/index.html.erb
<div class="banner foo">
  <div class="banner-content">
    <h1>Mister Cocktails</h1>
    <p>List and create all cocktails you can desire !</p>
<div class="banner-img"><%= cl_image_tag("mister cocktails/920a786b.png", :width=>98, :crop=>"scale") %></div>
    <div>
      <%= link_to 'Create cocktails', new_cocktail_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

  <div class="container text-center">
    <div class="row">
      <div class= "col-sm">
        <ul  class="list-inline">
          <% @cocktails.each do |cocktail| %>
            <li  class="list-inline-item">
              <div class="cards tagg" style="background-image: linear-gradient(to bottom right, lightblue, rgba(10,0,80,0.1)), url(http://quizz.fr/files/2012/09/cocktail.jpg) ">
                <span class="cards-category">Mister Cocktails</span>
                <div class="cards-description">
                  <h2><%= cocktail.name %></h2>
                  <div class="crud-line">
                    <%= link_to 'View détails', cocktail_path(cocktail[:id]) %>
                    <%= link_to 'Update', cocktail_path(cocktail[:id]) %>
                    <%= link_to 'Delete', cocktail_path(cocktail[:id]), method: :delete  %>
                  </div>
              </div>
            </div>
            </li>
          <% end %>
        </ul>
      </div><!--fin col-xs-12 -->
    </div>
  </div><!--fin container -->

app/views/cocktails/new.html.erb
<%= render 'cocktails/form' %>

app/views/cocktails/show.html.erb
<section class="offset-top">
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="dose-form-box">
          <div class="photo">
            <h2><%= @cocktail.name %></h2>
            <%= cl_image_tag @cocktail.photo, crop: :fill %>
          </div>
          <div class="formul">
            <ul>
            <% @cocktail.doses.each do |dose| %>
              <% if dose.persisted? %>
              <li>
                <p><%= dose.ingredient.name %> : <%= dose.quantitée %>
                  <%= link_to '[ X ]', dose_path(dose), method: :delete %>
                </p>
              </li>
              <% end %>
            <% end %>
            </ul>
            <div><%= render 'doses/form' %></div>
            <%= @cocktail.description %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="crud-links">
    <%= link_to 'Delete this cocktail', cocktail_path(@cocktail), method: :delete  %>
    <%= link_to 'Update this cocktail', edit_cocktail_path(@cocktail) %>
  </div>
</section>

app/views/cocktails/update.html.erb
<%= render 'cocktails/form' %>

app/views/doses/_form.html.erb
<div class="col-sm-6">
  <div class="form left">
    <h6>Add Ingredients</h6>
      <%= simple_form_for [@cocktail, @dose] do |f| %>
      <%= f.input :ingredient_id, collection: Ingredient.all %>
      <%= f.input :quantitée, placeholder: 'How much ?' %>
      <%= f.submit %>
    <% end %>
  </div>
</div>
<div class="right">  </div>

app/views/doses/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
      <%= stylesheet_link_tag  "application" %>
      <%= javascript_include_tag  "application" %>
      <%= csrf_meta_tags %>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  </head>
  <body>
    <style>
      #overlay {
        background: #ffffff;
        color: #666666;
        position: fixed;
        height: 100%;
        width: 100%;
        z-index: 5000;
        top: 0;
        left: 0;
        float: left;
        text-align: center;
        padding-top: 25%;
      }
    </style>

  <div id="overlay">
    <img src="../../../assets/loader.gif" alt="Loading" /><br/>
    Loading...
  </div>

    <%= render 'layouts/components/navbar' %>
    <%= yield %>
    <%= render'layouts/components/footer' %>

  <script>
    jQuery(window).load(function(){
    jQuery('#overlay').fadeOut();
    });
  </script>
  <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/layouts/components/_card.html.erb
<div class="cards">
  <span class="cards-category">POPULAR</span>
    <div class="cards-description">
    <h3>title2</h3>
    <p>some stuff here</p>
  </div>
  <img src="http://placehold.it/50x50" alt="" class="avatar cards-image">
</div>

app/views/layouts/components/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/layouts/components/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag('daiquiri')  %>
  </a>

  <!-- Right Navigation -->
  <div class= "navdate">Today is : <%= Date.today %></div>
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to 'All cocktails', root_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to 'Create cocktails', new_cocktail_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to 'Messages',  new_cocktail_path, class: "navbar-wagon-item navbar-wagon-link" %>


    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/backseo" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to 'All cocktails', root_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to 'All cocktails', root_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to 'Create cocktails', new_cocktail_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to 'Messages', new_cocktail_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
      </ul>
    </div>
  </div>
</div>